apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: prod
  name: php-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: php-app
  template:
    metadata:
      labels:
        app: php-app
    spec:
      containers:
      - name: php-app
        image: 471112907684.dkr.ecr.ap-south-1.amazonaws.com/rajack:latest
        ports:
        - containerPort: 80
        env:
        - name: MYSQL_HOST
          value: mysql-service
      readinessGates:
      - conditionType: target-health.alb.ingress.k8s.aws/k8s-phpapp-phpapp-d5c7858ec5
      terminationGracePeriodSeconds: 70
        lifecycle:
          preStop:
            exec:
              command: ["/bin/sh", "-c", "sleep 40"]
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 3
      maxSurge: 1  
        
